### ISSUE TITLE
Create Tables

### ISSUE THREAD

**Issue by BetOnJeanette** [BetOnJeanette/Database-project-team10#1]
|Create Tables|
|---|
|Create the tables for Categories and Tasks. These tables will follow the ERD we created for assignment 1|
![ERD](https://user-images.githubusercontent.com/67488504/99843486-a10f4a80-2b3f-11eb-897d-e74a549a1171.png)

**Comment by SamaramaX** [comment]
`CREATE TABLE Tasks (
     task_id INT,
     task_description VARCHAR (255),
     due_date DATE,
     category_id VARCHAR (255),
     priority_level INT,
     is_Complete VARCHAR (255),
     PRIMARY KEY (task_id),
     FOREIGN KEY (category_id) REFERENCES Categories(category_id)
);

CREATE TABLE Categories (
     category_id INT,
     name VARCHAR (255),
     PRIMARY KEY (category_id)
);`

**Comment by BetOnJeanette** [comment]
> `CREATE TABLE Tasks (
> task_id INT,
> task_description VARCHAR (255),
> due_date DATE,
> category_id VARCHAR (255),
> priority_level INT,
> is_Complete VARCHAR (255),
> PRIMARY KEY (task_id),
> FOREIGN KEY (category_id) REFERENCES Categories(category_id)
> );

category_id has to be an int to cooperate with the foreign key constraint, since the ID is an int on the other table. Also, is complete will be a boolean value: True if it's complete, false if otherwise.

**Comment by BetOnJeanette** [comment]
The tables are created
